project:
  type: website

website:
  title: "Ruoqian Wu"
  navbar:
    left:
      - text: Research
        href: research.qmd
      - text: Code & Tutorials
        href: experience.qmd
      - text: About Ruoqian
        href: about.qmd
      - text: Daily Life
        href: daily.qmd

format:
  html:
    theme: cosmo
