---
title: "Research&Teaching"
---

Updated on Feb 2026

## Current Research

My current research focuses on evaluating factor retention methods for continuous and categorial data in large factor models. This project, conducted under the supervision of [Prof. Yan Xia](https://education.illinois.edu/profile/yan-xia) was presented at IMPS 2025 and NCME 2026. I am currently working on the manuscript and my Master thesis.

A major challenge of this project involves conducting large-scale Monte Carlo simulations. To address this, I developed custom R code specifically designed to run SEM-based simulations efficiently on a Linux system. These simulations are executed on the [High-Performance Computing (HPC)](https://docs.ncsa.illinois.edu/systems/icc/en/latest/index.html) cluster at UIUC, which significantly accelerates computation(60x) and enables greater scalability. To support others working on similar projects, I am also writing a step-by-step tutorial on how to run Monte Carlo simulations for SEM in R from the Linux shell on HPC systems — available under the [Code & Tutorials](experience.qmd) tab.


- **Wu, R.**.(Master thesis). Factor retention in large binary and ordinal models: Evaluating parallel analysis, exploratory graph analysis,machine learning and their variants.
- **Wu, R.**, & Xia, Y. (in prep). *Which factor retention method is best for large factor models? A simulation study comparing 15 techniques in the Large Factor Model.*
- **Wu, R.**, Zhou, X.,& Xia, Y. (accepted). Factor retention in large binary and ordinal models:Evaluating parallel analysis, exploratory graph analysis, and their variants. Proposal acceptedfor presentation at the annual meeting of the National Council on Measurement in Education (NCME 2026).
- **Wu, R.**, & Xia, Y. (2025, July). *Which factor retention method is best for large factor models? A simulation study comparing 15 techniques in the Large Factor Model.* Poster presented at the International Annual Meeting of the Psychometric Society (IMPS 2025), Minneapolis, MN.





---


## Applied quantitative psychology in Real-World Contexts

My third research interest involves applying quantitative psychology to real-world, complex datasets. Recently, I worked on a project that used Confirmatory Factor Analysis (CFA) to examine intensive nominal data from young students’ writing.


- McKenna, M., Bottalico, P.,**Wu, R.**, Xia, Y., & Gerde, H. (July, 2025). *Characteristics of Kindergarten Sentence Structure Across Three Writing Genres.* In *Innovative Approaches to Examining Young Children’s Writing Development and Assessment from Preschool to Grade Five*, symposium presented at the Society for the Scientific Study of Reading Annual Meeting, Calgary, Canada.

---

## My First Introduction to SEM, First Research Project, and First Publication as an Undergraduate

During my undergraduate years, I used SEM to examine multiple mediating pathways linking emotional labor, well-being, emotional exhaustion, and turnover intentions. I translated an existing scale into Chinese and validated it through EFA and CFA, and I also contributed to the introduction, discussion, formatting, and reference citations for the publication paper. This project began in the second month of college and continued through the completion of my undergraduate thesis. Through this experience, I discovered my passion for research and developed the aspiration to pursue a PhD in quantitative psychology.


- Xie, Q., **Wu, R**., Chen, Y., Xue, M., Chen, Y., Wu, S., & Cai, J. (2023). *The impact of emotional labor on turnover intention among kindergarten teachers: Multiple mediating effects of emotional exhaustion and occupational well-being.* *Teacher Education Research, (3)*, 74–81. [https://doi.org/10.13445/j.cnki.t.e.r.2023.03.014](https://doi.org/10.13445/j.cnki.t.e.r.2023.03.014)

## Collaborative Work

I feel very fortunate to be part of such a supportive lab with wonderful peers and a positive, collaborative environment.In our collaborative work, I mainly contribute to the computational side, especially using high-performance computing (HPC) to run simulations, manage large-scale analyses, and support our research projects.

- Zhou, X., **Wu, R.**, & Xia, Y. (accepted). Parametric and nonparametric bootstrapping in exploratory factor analysis with multiple imputation. Proposal accepted for presentation at the annual meeting of the National Council on Measurement in Education (NCME 2026).

- Project: Impact evaluation with latent variables: using factor scores and data mining methods in propensity score matching Funded by Spencer Foundation ($49,879)
PIs: Prof. Yan Xia & Prof. Ge Jiang(Role:Graduate research assistant)


## Teaching experience

In Spring 2026, I am serving as a Teaching Assistant for [(EPSY 581: Applied Regression Analysis)](https://education.illinois.edu/course/EPSY/581). My responsibilities include grading assignments and holding office hours to assist students in developing their understanding of regression methods. I enjoy supporting students’ learning and welcome attend my office hours. 🤩

EPSY 581 introduces core concepts in regression and statistical modeling, including basic linear algebra, the general linear model, coding schemes, regression diagnostics, and extensions to binary and nested data structures. The course is cross-listed with PSYC 581.